version: '3'
services:
  app:
    container_name: app
    build: ./spring-boot-prometheus
    ports:
      - "8080:8080"
    networks: 
      - app_net
networks: 
  app_net:
    name: app_net
    external: true