version: '3'
services:
  prometheus:
    container_name: prometheus
    image:
      prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./volumes/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./volumes/first.rules:/etc/prometheus/first.rules
    networks: 
      - app_net
#  alertmanager:
#    image:
#      prom/alertmanager
#    volumes:
#      - ./volumes/alertmanager.yml:/prometheus/alertmanager.yml
#    command:
#      - '--config.file=/prometheus/alertmanager.yml'
#    ports:
#      - "9093:9093"
#    depends_on: 
#      - prometheus
#    networks: 
#      - app_net
  grafana:
    container_name: grafana
    image:
      grafana/grafana
    ports:
      - "3000:3000"
    environment: 
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ./volumes/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    depends_on: 
      - prometheus
    networks: 
      - app_net
networks: 
  app_net:
    name: app_net
    driver: bridge